artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion     # thi is the root folder where the entire data ingestion(downloads data) stores
  source_URL:  https://github.com/jimschacko/Advanced-Text-Summarizer/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip       # after downloading the data the zip file will get stored in this path
  unzip_dir: artifacts/data_ingestion            #after unzipping it will store in this path



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


  model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv